#!/bin/bash
pid=$(pidof ssh-agent)
if [ ! -z $pid ]; then
	pkill $pid
fi

envfile=$HOME/.ssh/environment
bashrc=$HOME/.bashrc

ssh-agent > "$envfile"

grep ". $envfile" "$bashrc" || echo ". $envfile" >> "$bashrc"
